/** Source id → display name shown on company badges and filters. */
export const sourceNames: Record<string, string> = {
  google: "Google",
  meta: "Meta",
  netflix: "Netflix",
  uber: "Uber",
  airbnb: "Airbnb",
  spotify: "Spotify",
  slack: "Slack",
  dropbox: "Dropbox",
  pinterest: "Pinterest",
  notion: "Notion",
  figma: "Figma",
  stripe: "Stripe",
  shopify: "Shopify",
  discord: "Discord",
  cloudflare: "Cloudflare",
  github: "GitHub",
  etsy: "Etsy",
  linkedin: "LinkedIn",
  coinbase: "Coinbase",
  doordash: "DoorDash",
  instacart: "Instacart",
  lyft: "Lyft",
  canva: "Canva",
  datadog: "Datadog",
  paypal: "PayPal",
  booking: "Booking.com",
  duolingo: "Duolingo",
  yelp: "Yelp",
  grab: "Grab",
  atlassian: "Atlassian",
  openai: "OpenAI",
  anthropic: "Anthropic",
  deepmind: "Google DeepMind",
  huggingface: "Hugging Face",
  "aws-architecture": "AWS Architecture Blog",
  "aws-news": "AWS News Blog",
  cockroachlabs: "Cockroach Labs",
  databricks: "Databricks",
  instagram: "Instagram Engineering",
  janestreet: "Jane Street",
  line: "LINE Engineering",
  nvidia: "NVIDIA Developer Blog",
  twitch: "Twitch",
};

export function sourceName(id: string): string {
  return sourceNames[id] ?? id;
}
