/** Source id → display name shown on company badges and filters. */
export const sourceNames: Record<string, string> = {
  meta: "Meta",
  netflix: "Netflix",
  uber: "Uber",
  airbnb: "Airbnb",
  spotify: "Spotify",
  slack: "Slack",
  dropbox: "Dropbox",
  pinterest: "Pinterest",
  notion: "Notion",
  figma: "Figma",
  stripe: "Stripe",
  shopify: "Shopify",
  discord: "Discord",
  cloudflare: "Cloudflare",
  github: "GitHub",
  linkedin: "LinkedIn",
  coinbase: "Coinbase",
  lyft: "Lyft",
  canva: "Canva",
  datadog: "Datadog",
  paypal: "PayPal",
  booking: "Booking.com",
  duolingo: "Duolingo",
  yelp: "Yelp",
  grab: "Grab",
  atlassian: "Atlassian",
  openai: "OpenAI",
  "aws-architecture": "AWS Architecture Blog",
  instagram: "Instagram Engineering",
  janestreet: "Jane Street",
  line: "LINE Engineering",
  nvidia: "NVIDIA Developer Blog",
  manual: "Manual",
};

export function sourceName(id: string): string {
  return sourceNames[id] ?? id;
}
